services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_URI: ${MONGO_URI}

  machine-learning-client:
    build: ./machine-learning-client
    env_file:
      - .env
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: ${MONGO_URI}

  web-app:
    build: ./web-app
    env_file:
      - .env
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://root:example@mongodb:27017"
    volumes:
      - ./web-app/src:/app

volumes:
  mongodb_data: