name: Machine Learning Client CI

on:
  push:
    paths:
      - 'machine-learning-client/**'
  pull_request:
    paths:
      - 'machine-learning-client/**'

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: machine-learning-client

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    env:
      SECRET_KEY: test_secret_key
      MONGO_DBNAME: test_db
      MONGO_URI: mongodb://localhost:27017/test_db
      ML_CLIENT_URL: http://fake-ml-client

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Format Code with Black
        run: |
          black src/*.py
          black *.py

      - name: Lint Code with Pylint
        run: |
          pylint src/*.py
          pylint *.py

      - name: Run tests
        run: pytest --cov=src --cov-report=term-missing